name: Publish VSIX to GitHub Releases

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Set version tag
        run: |
          $GITHUB_ENV=$(jq '.version' ./package.json)
          git config --global user.name "ibeloyar-action"
          git config --global user.email "beloyar.dev@outlook.com"
          git tag v$GITHUB_ENV
          git push origin v$GITHUB_ENV

      - name: Build VSIX
        run: npx vsce package

      - name: Upload VSIX to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: fir-dark-theme-*.vsix
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}